source 'https://rubygems.org'

gem 'rails', '~> 4.1.7'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'activerecord-jdbcsqlite3-adapter'
gem 'active_model_serializers', "0.9.0"
gem 'jruby-openssl'

# Gems used only for assets and not required
# in production environments by default.
#gem 'sass-rails',   '~> 4.0.4'
#gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
#gem 'therubyrhino'
gem 'uglifier', '>= 1.3.0'
gem 'tzinfo-data'

#gem 'jquery-rails'
#gem 'underscore-rails', "~> 1.5.2"
#gem 'handlebars-source', '~> 1.0.12'
#gem 'ember-rails'
#gem 'ember-source', '1.1.2'
#gem 'jquery-ui-rails'
#gem 'dynatree-rails'
#gem 'uri-js-rails'
gem 'themoviedb', '0.0.22'

gem 'sunspot_rails'
gem 'sunspot_solr' # optional pre-packaged Solr distribution for use in development

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
gem 'class-table-inheritance'
gem 'flexmock', :require => false # manual require in test files or db migrations break...

gem 'torquebox', '3.1.1'